name: Origyn - Origyn-ART-UI package publishing

on:
  push:
    tags:
      - '*origyn_art_ui*'

jobs:
  origyn-art-ui-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout commits for ${{ steps.extract_branch.outputs.branch }} branch
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Origyn_ART_UI - install dependencies
        run: |
          npm ci
          npm i -g jest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Origyn_ART_UI - build
#        run: |
#          npm run build
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#      - name: Origyn_ART_UI - testing
#        run: |
#          npm run test
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Origyn_ART_UI - publishing dev
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
